### ISSUE TITLE
blastp file in phylogenetics

### ISSUE THREAD

**Issue by xing-he529** [SysBioChalmers/HGTphyloDetect#1]
Hi, 
It's a nice tool for HGT detecting!!!

but I got this error when i used example file "HGTphyloDetect/example/blastp_files/AAT92670.txt" to run phylogenetics step.

And i found that the format of two blastp files in your example(YOL164W.txt, AAT92670.txt) is different, so i guess it's the reason why i get this error.
i'm wondering how can i get the blastp file like "YOL164W.txt" , or can you give me some advices ？

> This is gene AAT92670 
> Begin to run!!!
> This is gene AAT92670 ---------------
> Traceback (most recent call last):
>   File "/home/xinghe/data/Alvinellidae/HGT/3/phylogenetics/scripts/HGT_homologs_sequence.py", line 151, in <module>
>     main()
>   File "/home/xinghe/data/Alvinellidae/HGT/3/phylogenetics/scripts/HGT_homologs_sequence.py", line 87, in main
>     accession_number, accession_similarity = parse_NCBI("./input/%s.txt" % gene)
>   File "/home/xinghe/data/Alvinellidae/HGT/3/phylogenetics/scripts/HGT_homologs_sequence.py", line 22, in parse_NCBI
>     accession = line.strip("\n").split("\t")[2]
> IndexError: list index out of range
> /usr/local/bin/mafft: Cannot open ./input/AAT92670_homologs.fasta.
> 
> /usr/local/bin/mafft: line 1270: /tmp/mafft.PsSNzDZxo9/infile: No such file or directory
> awk: fatal: cannot open file `/tmp/mafft.PsSNzDZxo9/size' for reading (No such file or directory)
> awk: fatal: cannot open file `/tmp/mafft.PsSNzDZxo9/size' for reading (No such file or directory)
> /usr/local/bin/mafft: line 1274: [: too many arguments
> /usr/local/bin/mafft: line 1279: [: too many arguments
> /usr/local/bin/mafft: line 1284: [: too many arguments
> /usr/local/bin/mafft: line 1289: [: -lt: unary operator expected
> /usr/local/bin/mafft: line 1294: [: -lt: unary operator expected
> /usr/local/bin/mafft: line 1301: [: -lt: unary operator expected
> /usr/local/bin/mafft: line 1308: [: -lt: unary operator expected
> ------------------------------------------------------------------------------
>   MAFFT v7.505 (2022/Apr/10)
>   https://mafft.cbrc.jp/alignment/software/
>   MBE 30:772-780 (2013), NAR 30:3059-3066 (2002)
> ------------------------------------------------------------------------------
> High speed:
>   % mafft in > out
>   % mafft --retree 1 in > out (fast)
> 
> High accuracy (for <~200 sequences x <~2,000 aa/nt):
>   % mafft --maxiterate 1000 --localpair  in > out (% linsi in > out is also ok)
>   % mafft --maxiterate 1000 --genafpair  in > out (% einsi in > out)
>   % mafft --maxiterate 1000 --globalpair in > out (% ginsi in > out)
> 
> If unsure which option to use:
>   % mafft --auto in > out
> 
> --op # :         Gap opening penalty, default: 1.53
> --ep # :         Offset (works like gap extension penalty), default: 0.0
> --maxiterate # : Maximum number of iterative refinement, default: 0
> --clustalout :   Output: clustal format, default: fasta
> --reorder :      Outorder: aligned, default: input order
> --quiet :        Do not report progress
> --thread # :     Number of threads (if unsure, --thread -1)
> --dash :         Add structural information (Rozewicki et al, submitted)
> 
> ERROR: Alignment not loaded: "./intermediate/AAT92670_aln.fasta" Check the file's content.
> 
> IQ-TREE multicore version 2.1.2 COVID-edition for Linux 64-bit built Oct 22 2020
> Developed by Bui Quang Minh, James Barbetti, Nguyen Lam Tung,
> Olga Chernomor, Heiko Schmidt, Dominik Schrempf, Michael Woodhams.
> 
> Host:    7525B (AVX2, FMA3, 502 GB RAM)
> Command: iqtree2 -T 40 -nt 6 -st AA -s ./intermediate/AAT92670_aln_trimmed.fasta -m TEST -mrate G4 -keep-ident -bb 1000 -pre ./intermediate/AAT92670
> Seed:    425967 (Using SPRNG - Scalable Parallel Random Number Generator)
> Time:    Thu Feb 16 21:08:22 2023
> Kernel:  AVX+FMA - 6 threads (256 CPU cores detected)
> 
> Reading alignment file ./intermediate/AAT92670_aln_trimmed.fasta ... ERROR: File not found ./intermediate/AAT92670_aln_trimmed.fasta
> code for methods in class “Rcpp_Fitch” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
> code for methods in class “Rcpp_Fitch” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
> Warning message:
> package ‘phangorn’ was built under R version 4.2.2 
> [1] "AAT92670"
> Error in file(file, "r") : cannot open the connection
> Calls: read.tree -> scan -> file
> In addition: Warning message:
> In file(file, "r") :
>   cannot open file './intermediate/AAT92670.treefile': No such file or directory
> Execution halted
> perl: error while loading shared libraries: libnsl.so.1: cannot open shared object file: No such file or directory
> Yep, finish!!!

Thanks！
XingHE

**Comment by le-yuan** [comment]
Thanks for your interest. Exactly, this issue is that you used a different format of blastp files when running the phylogenetic analysis part. I would suggest you to use the same format of the blastp file under the phylogenetics directory. To generate that kind of blastp file, you can run blastp by using **diamond** with the parameters 
`-k 300 -f 6 qseqid qlen sseqid pident length evalue bitscore`

 But I think NCBI blastp can also generate the blastp file with this format, you can explore how to do that if you want.

**Comment by xing-he529** [comment]
Thanks for your reply, it works!😁
