### ISSUE TITLE
An issue regrading duplication

### ISSUE THREAD

**Issue by herman-einstein** [SysBioChalmers/HGTphyloDetect#10]
When I ran more than a thousand samples, there may be several identical accession numbers with different e-values and identities. It results in the inconsistency of the number of accession similarity and accession number in your script, HGT_homologs_sequence.py.

**Comment by le-yuan** [comment]
Hi,

I think the issue regarding duplication in sequence homologs searching would not occur in the script. If you want to run the program for more than one thousand samples, there are two solutions for you to consider: 

1) you can split your samples into 1000 individual files, and then run the script like that: 
**python scripts/HGT_homologs_sequence.py input/gene1.fasta**
**python scripts/HGT_homologs_sequence.py input/gene2.fasta**
**python scripts/HGT_homologs_sequence.py input/gene3.fasta**
It is easy to manipulate by writing scripts, which can be implemented via less than ten lines.

2) You can also look through the script **HGT_homologs_sequence.py**, and just change a few lines based on your own requirement, which is not difficult.

Best regards,
Le
