### ISSUE TITLE
HGTPhyloDetect : Not working with GenBank Accession ID

### ISSUE THREAD

**Issue by SB-bioinfo1992** [SysBioChalmers/HGTphyloDetect#14]
Error : This is gene 1------------------
AAF38644
Yes, blast file already exists, nice!
Attention: please check the gene accession id!

Here AAF38644 is a GenBank id of Q9Z6R0 (Uniprot). I have also tried with alternative GenBank accession, but the results are same.

**Comment by le-yuan** [comment]
I guess that you GenBank ID AAF38644 does not have subphylum taxonomy id, so HGTPhyloDetect can not run the pipeline properly.

**Comment by SB-bioinfo1992** [comment]
Can you please elaborate on what do you mean by "GenBank ID AAF38644 does not have subphylum taxonomy id"? Probably an example would be better.

**Comment by le-yuan** [comment]
For instance, running the pipeline for the GenBank ID AHJ11290.1 retrieves the following taxonomy information: {'superkingdom': 2, 'phylum': 29547, 'class': 3031852, 'order': 213849, 'family': 2932623, 'genus': 57665, 'species': 66821, 'strain': 1150621}. If there is no subphylum-related ID available, an error will be triggered.

**Comment by SB-bioinfo1992** [comment]
I think this information are not stored in GenBank and needs to be retrieved from NCBI taxonomy. If that's the case, you can get the unique id for all the taxonomic sub-levels.

**Comment by le-yuan** [comment]
Yes, we used ETE tools to extract the taxonomy information based on GenBank id. If the information is stored or updated in NCBI taxonomy, we should be able to obtain the info and make the HGT identification.
