### ISSUE TITLE
BLAST hits of proteins with no subphylum or kingdom taxonomy from NCBI

### ISSUE THREAD

**Issue by BRYZAL** [SysBioChalmers/HGTphyloDetect#15]
So I have tried to run this workflow but unfortunately I ran to an issue that was raised before. Which is that some BLAST hits do not have subphylum or kingdom listed in the NCBI taxonomy database (example below). Is there a way around this or a different approach that was presented? Is there a particular reason it has to be subphylum and kingdom?

Error : This is gene 1------------------
AAF38644
Yes, blast file already exists, nice!
Attention: please check the gene accession id!

**Comment by le-yuan** [comment]
Sorry for my delayed response! I think the issue could be resolved by tweaking the script to modify the subphylum and kingdom. In the pipeline reported in my work, I adopted a strategy similar to what's described in the Cell paper namely [Tempo and Mode of Genome Evolution in the Budding Yeast Subphylum](https://www.cell.com/cell/fulltext/S0092-8674(18)31332-1). You might find it helpful to take a look at that.
