### ISSUE TITLE
Hypothetical protein management and HGT: is it feasible to use proxy IDs?

### ISSUE THREAD

**Issue by Leytoncito** [SysBioChalmers/HGTphyloDetect#16]
Dear @le-yuan,

I am writing to express my interest in using this tool in my research. I am aware that you have covered the topic of GenBank IDs for proteins and their role in determining taxonomy in several issues. As microbiologists, we frequently encounter a challenge when using automatic annotators such as Bakta or Prokka. These tools often do not provide all the necessary GenBank IDs, which is an issue we would like to see addressed.
Furthermore, a significant number of recombinant proteins (i.e. those with horizontal gene transfer or HGT traces) lack sufficient characterisation and are typically classified as hypothetical, often corresponding to uncharacterised mobile genetic elements (MGEs). It is, however, these proteins that present the most interesting case for evaluation in terms of recombination.
Nevertheless, I am convinced that this tool offers the most logical solution and I am determined to use it. I am exploring two potential avenues for utilising your tool:

1) Prior to running your pipeline, I would perform a BLASTP of my protein of interest, selecting the best hit as the input.
2) As an alternative, I could provide the pipeline with a GenBank ID that has the desired taxonomy. For instance, I could use the ID of a 16S rRNA from Corynebacterium striatum. My understanding is that your tool only requires one way to extract a taxonomy, given that the comparison is done at the sequence level.

I'm especially interested in whether the second method might be viable, given that we sometimes face proteins without good hits in BLAST.

Finally, I would like to know:  How many queries can I make without saturating the ncbi database. That is to say before it penalizes me and blocks me.

I really appreciate your time and any guidance you can provide.

Best regards

Benjamin

**Comment by le-yuan** [comment]
Yes, it is doable to adopt the second method that you suggested, feel free to try it.
