### ISSUE TITLE
i am getting error while running HGT_workflow

### ISSUE THREAD

**Issue by tanusaroha** [SysBioChalmers/HGTphyloDetect#3]
when i run command for my gene, i get error please check gene accesion id. 
python HGT_workflow.py input.fasta
This is gene 1------------------
NG_048001
Yes, blast file already exists, nice!
Attention: please check the gene accession id!

**Comment by tanusaroha** [comment]
I have ncbi genbank file and taking protein accession id for the gene (that is refseq accession id)

**Comment by le-yuan** [comment]
Currently, the input protein id only applies to the GenBank database. If you are interested, you can use the protein accession id in GenBank to try the prediction. But in the next update, we will also consider other protein ids from RefSeq.

**Comment by tanusaroha** [comment]
I tried with protein genbank ID, still getting the same error.

**Comment by le-yuan** [comment]
Could you please tell me more information about your protein GenBank ID, I can help to check it.
