### ISSUE TITLE
New protein used for HGT

### ISSUE THREAD

**Issue by JianjiaDTU** [SysBioChalmers/HGTphyloDetect#5]
In the readme, it  notes that protein id should be from the GenBank  protein database. But if I denovo assembled an new genome. Then I want to detect the HGT gene in the NCBI database. How should I deal with this problem. In a word, if I just want to calculate the AI value for the new protein. is it ok for me?

**Comment by le-yuan** [comment]
Maybe you are the person who contacted us by email before, but I also post my response here for reference.

Thanks for your interest. For your new proteins, it is also possible to detect HGT events by using HGTphyloDetect. There are two possible solutions we can offer you, depending on your programming background:

(1) If you have basic Python programming skills, you can modify the code in HGT_workflow.py to define the kingdom and subphylum based on your input protein. In the ReadMe file, we mentioned that the protein ID should be from the GenBank protein database to allow the program to automatically determine the kingdom and subphylum information. However, for your new proteins, you will need to manually input this information;

(2) If you have no programming background, you can use a protein ID that is very similar to your query protein in the phylogeny (but keep your original sequence and only change the protein ID that can be found by the program). The input protein ID in HGTphyloDetect is primarily used to detect the clade of the query protein and then divide those protein hits into ingroup and outgroup from the Blastp process. Therefore, using a similar protein ID should work.

**Comment by maruiqi0710** [comment]
老师您好，我遇到了同样的问题，请问我应该修改HGT_workflow.py中的哪一行代码？应如何修改？可否给个示例，是给出物种编号还是gene编号？谢谢！
