### ISSUE TITLE
How to modify the code in HGT_workflow.py to define the kingdom and subphylum based on my input protein. 

### ISSUE THREAD

**Issue by maruiqi0710** [SysBioChalmers/HGTphyloDetect#7]
I have the same question as in [https://github.com/SysBioChalmers/HGTphyloDetect/issues/5](https://github.com/SysBioChalmers/HGTphyloDetect/issues/5) . How do I modify the code in HGT_workflow.py？Could give an example? Should I provide a species number or a gene number? Thank you!！

**Comment by le-yuan** [comment]
Hi, sorry for the late reply. 

Currently I don't have such an example, but it is relatively easy. If you input protein is a new protein, you can use a similar protein ID that has the same kingdom and the same subphylum, then our program could output the same predicted result for you.

In the next version of our HGTphyloDetect software, we will provide this kind of example and make it more user-friendly and much faster. Thanks for your attention!

Best regards,
Le
