### ISSUE TITLE
Gene accession id not recognized. 

### ISSUE THREAD

**Issue by MCeelen** [SysBioChalmers/HGTphyloDetect#8]
Thank you for publishing this tool. In principle it could be very useful for my research. However,
I'm not able to get it to work. Every protein I put in gives the 'Attention: please check the gene accession id!' error

When I try to run the programme with the example fasta file without the pregenerated blast file I get the following error:
This is gene 1------------------
AAT92670
Traceback (most recent call last):
  File "/Users/marijn/HGTphyloDetect/example/HGT_workflow.py", line 212, in <module>
    main()
  File "/Users/marijn/HGTphyloDetect/example/HGT_workflow.py", line 114, in main
    for accession in accession_number[:200] :
UnboundLocalError: local variable 'accession_number' referenced before assignment.

Other proteins I tried are for example Q1DFT5 and Q50900, these give the 'Attention: please check the gene accession id!' error.

Do you know how to solve this issue?
Thank you in advance!

**Comment by le-yuan** [comment]
Thanks for trying our computational tool. 

If you try to run the programme with the example fasta file without the pre-generated blast file, then one error was out shown as above. After checking the logs, I think: 1) Firstly, you can check whether the blast file was generated after running this program although one error was out. If there exist such a blast file, it means that the code before line 114 has no any issues and blastp has been run normally for the case. 2) If there exist such a blast file, but one error occurs like that, then you can add one line **accession_number,evalue = parse_NCBI(gene**) in line 89 after **line 88 os.system(myCmd)** with the same identification. 

For our second issue, you are now trying Q1DFT5 and Q50900, it looks like that these two proteins are **Uniprot ID**. However, the program now only supports gene/protein ID from the GeneBank database. But in the next version, we will also try to integrate the Uniprot ID.

Thank you!

Best regards,
Le
