### ISSUE TITLE
the format of example, "YOL164W.txt" is not consistent

### ISSUE THREAD

**Issue by herman-einstein** [SysBioChalmers/HGTphyloDetect#9]
the format of example, "YOL164W.txt"  is not as same as the format that blastp.py generated. Therefore, I got error when I ran my sample using generate_tree.sh

**Comment by aldendirks** [comment]
I have the same issue. It is unclear to me what the formatting of YOL164W.txt is and how I can convert the blastp.py txt output to match this.

**Comment by le-yuan** [comment]
Hello, the **"YOL164W.txt"** file was not created by the blastp.py. But you can generate this txt file using the Blastp function in Diamond, which can speed up your running process.
